### ISSUE TITLE
Create base repo for profile package

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#182]
## Overview

The goal is to have a new repository created that will be imported on both App Telos and Telos Wallet for the profile component at first. This is the initial task, so we want a npm package repository that can be imported by the projects.

## Acceptance criteria

- New repository created
- Code can be imported as an NPM package from other repos
- Unit testing setup
- ESLint setup
- Vue and Quasar dependencies

## Technical considerations

We'll be using the updated version of Vue and Quasar.

## Tasks

- [ ] Create the repository
- [ ] Run unit tests with CI/CD and locally
- [ ] Import it to another project

**Comment by karynemayer** [comment]
We won't be addressing this anytime soon since this is the new plan #https://github.com/telosnetwork/epics/issues/9
