### ISSUE TITLE
BallotView should support DCMS-v2 and not-opened ballots

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#206]
## Overview
The new wizard for ballot creation incorporates the protocol [DCMS v2](https://github.com/telosnetwork/telos-decide/blob/master/dcms-v2.md) but the current implementation on BallotListItem does not support it completely yet. The new wizard also allows the creation of the poll without actually opening it immediately for voting and that state is still not supported.

## Acceptance criteria
The BallotView should fully support the new criteria for storing ballots metadata defined in [DCMS v2](https://github.com/telosnetwork/telos-decide/blob/master/dcms-v2.md). Not only the image and PDF can be stored differently but also a set of displayable names may be added as metadata too (optionally).
Finally if the ballot is not open for voting yet, it should reflect that situation and bring an "Open for Voting" button for the manager of the ballot.

## Tasks
- [x] properly extract and show the image
- [x] properly extract and show the PDF
- [x] properly extract and show displayable-names for options (if defined)
- [x] manage the status of not yet open for voting
