### ISSUE TITLE
UI for managing DAO token features (transferable, stakeable, burnable, etc)

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#207]
## Overview
Currently the only meaning that DAOs have is the possibility of voting in a ballot created specifically for that community. However, in order to vote it is necessary to have a positive balance of its token, but by default, they are not transferable. This prohibits the users to be able to vote and that renders the entire DAO system useless.

We need to provide a solution to the DAO manager to change the whole token configuration.

## Acceptance criteria
The token creator must be able to access the list of available features for a DAO token and change them. That list includes the following features: `transferable`, `burnable,` `reclaimable,` `stakeable,` `unstakeable,` `maxmutable`

## Tasks
- [ ] create a component for encapsulating the checkbox list to enable/disable token features
- [ ] adapt the current Create-DAO dialog to include the new component and include the token feature settings in the DAO creation process.
- [ ] once created the DAO, it should show a button to popup a dialog with a form containing the new component to change token features.

**Comment by Viterbo** [comment]
Fixed and merged, so I close this issue
